# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            MK 
tagline:          MK's BLOG
description:      '足球迷，码农，vi布道者，文学爱好者，伪哲学爱好者, 伪艺术爱好者'
url:              http://ckitterl.github.io
baseurl:          /

author:
  name:           'mk'
  url:            https://twitter.com/ckitterl

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ckitterl

plugins: [jekyll-paginate]
